-- V9: outbox de e-mails transacionais.
-- A gravação acontece na MESMA transação do evento de negócio (ex.: recuperação de senha);
-- o scheduler (@Scheduled, apenas com pratoja.mail.enabled=true) processa linhas PENDING/FAILED
-- com next_attempt_at <= agora, com retry exponencial (1min, 5min, 15min) e DEAD após 5 tentativas.
-- Nenhuma credencial SMTP é armazenada aqui: configuração via ambiente (SMTP_HOST etc.).

CREATE TABLE mail_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_email VARCHAR(200) NOT NULL,
    template VARCHAR(100) NOT NULL,
    payload_json TEXT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    last_error VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP,
    CONSTRAINT ck_mail_outbox_status CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'DEAD'))
);

-- Consulta quente do scheduler: linhas vencidas por status/próxima tentativa.
CREATE INDEX idx_mail_outbox_status_next ON mail_outbox (status, next_attempt_at);
