package br.com.pratoja.pratoja.service;
import br.com.pratoja.pratoja.cart.*;
import br.com.pratoja.pratoja.domain.*;
import br.com.pratoja.pratoja.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.*;
@Service @RequiredArgsConstructor
public class OrderService {
    private final OrderRepository orders;private final AddressRepository addresses;private final ProductOptionRepository options;private final ProductRepository products;private final ReviewRepository reviews;private final CurrentUserService current;private final SessionCart cart;private final CartService cartService;private final RealtimeHub hub;
    /** Fase 4: a loja do pedido vem da rota /loja/{slug}; todo produto da sacola é validado contra ela. */
    @Transactional public Long place(Authentication auth,Store store,String fulfillment,Long addressId,String payment,String changeFor,String notes){User user=current.require(auth);
        List<CartLine> lines=cart.getLines(store.getId());if(lines.isEmpty())throw new IllegalArgumentException("Sua sacola está vazia.");
        DomainTypes.FulfillmentType type=parse(DomainTypes.FulfillmentType.class,fulfillment,"Forma de recebimento inválida.");DomainTypes.PaymentMethod method=parse(DomainTypes.PaymentMethod.class,payment,"Forma de pagamento inválida.");Address address=null;if(type==DomainTypes.FulfillmentType.DELIVERY)address=addresses.findById(addressId==null?-1:addressId).filter(a->a.getUser().getId().equals(user.getId())).orElseThrow(()->new IllegalArgumentException("Selecione um endereço de entrega."));
        List<CartLine> checked=new ArrayList<>();for(CartLine line:lines)try{checked.add(cartService.create(store.getId(),line.productId(),line.quantity(),line.choices().stream().map(CartLine.Choice::optionId).toList(),line.notes()));}catch(IllegalArgumentException e){if(products.findById(line.productId()).isPresent())throw new SecurityException();throw e;}
        // Isolamento: todo produto da sacola deve pertencer à loja em contexto (404 em caso contrário).
        for(CartLine line:checked)if(products.findByIdAndStore_Id(line.productId(),store.getId()).isEmpty())throw new SecurityException();
        BigDecimal subtotal=checked.stream().map(CartLine::total).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal delivery=type==DomainTypes.FulfillmentType.DELIVERY?store.getDeliveryFee():BigDecimal.ZERO;BigDecimal total=subtotal.add(delivery);BigDecimal change=null;if(method==DomainTypes.PaymentMethod.CASH&&changeFor!=null&&!changeFor.isBlank()){try{change=new BigDecimal(changeFor.replace(",","."));}catch(Exception e){throw new IllegalArgumentException("Valor para troco inválido.");}if(change.compareTo(total)<0)throw new IllegalArgumentException("O valor para troco deve cobrir o total.");}
        Order order=new Order();order.setUser(user);order.setStore(store);order.setAddress(address);order.setFulfillmentType(type);order.setStatus(DomainTypes.OrderStatus.RECEIVED);order.setSubtotal(subtotal);order.setDeliveryFee(delivery);order.setTotal(total);order.setNotes(clean(notes,600));
        for(CartLine line:checked){OrderItem item=new OrderItem();item.setOrder(order);item.setProduct(products.getReferenceById(line.productId()));item.setProductName(line.productName());item.setUnitPrice(line.unitPrice());item.setQuantity(line.quantity());item.setLineTotal(line.total());item.setNotes(line.notes());for(CartLine.Choice c:line.choices()){OrderItemOption io=new OrderItemOption();io.setOrderItem(item);io.setOption(options.getReferenceById(c.optionId()));io.setGroupName(c.groupName());io.setOptionName(c.name());io.setPriceDelta(c.price());item.getOptions().add(io);}order.getItems().add(item);}Payment pay=new Payment();pay.setOrder(order);pay.setMethod(method);pay.setChangeFor(change);pay.setStatus(method==DomainTypes.PaymentMethod.CASH?DomainTypes.PaymentStatus.CASH_ON_DELIVERY:DomainTypes.PaymentStatus.CONFIRMED);order.setPayment(pay);addHistory(order,DomainTypes.OrderStatus.RECEIVED,user.getEmail());orders.save(order);cart.clear(store.getId());hub.publish(order.getId(),store.getId(),order.getStatus().name());return order.getId();}
    @Transactional public OrderView view(Long id,Authentication auth,boolean admin){Order o=orders.findById(id).orElseThrow();User user=current.require(auth);if(!admin&&!o.getUser().getId().equals(user.getId()))throw new SecurityException();return map(o);}
    /** Tracking no contexto da rota /loja/{slug}: pedido precisa pertencer à loja da URL e ao cliente logado. */
    @Transactional public OrderView viewInStore(Long id,Authentication auth,Store store){Order o=orders.findById(id).orElseThrow(SecurityException::new);User user=current.require(auth);if(!o.getStore().getId().equals(store.getId())||!o.getUser().getId().equals(user.getId()))throw new SecurityException();return map(o);}
    /** Visão do admin restrita à loja em contexto: objeto de outra loja -> 404 (SecurityException). */
    @Transactional public OrderView adminView(Long id,Store store){Order o=orders.findByIdAndStore_Id(id,store.getId()).orElseThrow(SecurityException::new);return map(o);}
    @Transactional(readOnly=true)public List<OrderView> history(Authentication auth){User u=current.require(auth);return orders.findByUserIdOrderByCreatedAtDesc(u.getId()).stream().map(this::map).toList();}
    /** Painel do admin: apenas pedidos da loja em contexto. */
    @Transactional(readOnly=true)public List<OrderView> all(Store store){return orders.findAllByStore_IdOrderByCreatedAtDesc(store.getId()).stream().map(this::map).toList();}
    /** Cliente repete um pedido próprio dentro do contexto da loja da URL; pedido de outra loja -> 404. */
    @Transactional public String repeat(Long id,Authentication auth,Store store){User u=current.require(auth);
        Order o=orders.findByIdAndStore_Id(id,store.getId()).orElseThrow(SecurityException::new);
        if(!o.getUser().getId().equals(u.getId()))throw new SecurityException();int skipped=0;for(OrderItem i:o.getItems()){try{cart.add(store.getId(),cartService.create(store.getId(),i.getProduct().getId(),i.getQuantity(),i.getOptions().stream().map(x->x.getOption().getId()).toList(),i.getNotes()));}catch(Exception e){skipped++;}}return skipped==0?"Pedido adicionado à sacola.":"Itens disponíveis foram adicionados; "+skipped+" item(ns) não estão mais disponíveis.";}
    @Transactional public void review(Long id,Authentication auth,int rating,String comment){Order o=orders.findById(id).orElseThrow();User u=current.require(auth);if(!o.getUser().getId().equals(u.getId())||o.getStatus()!=DomainTypes.OrderStatus.DELIVERED||reviews.existsByOrderId(id)||rating<1||rating>5)throw new IllegalArgumentException("Este pedido não pode ser avaliado.");Review r=new Review();r.setOrder(o);r.setUser(u);r.setRating(rating);r.setComment(clean(comment,600));reviews.save(r);}
    @Transactional public void transitionInStore(Long id,Store store,DomainTypes.OrderStatus next,String actor){Order o=orders.findByIdAndStore_Id(id,store.getId()).orElseThrow(SecurityException::new);if(!allowed(o,next))throw new IllegalArgumentException("Transição de status inválida.");o.setStatus(next);o.setUpdatedAt(LocalDateTime.now());addHistory(o,next,actor);orders.save(o);hub.publish(id,store.getId(),next.name());}
    private boolean allowed(Order o,DomainTypes.OrderStatus n){if(n==DomainTypes.OrderStatus.CANCELLED)return o.getStatus()!=DomainTypes.OrderStatus.DELIVERED&&o.getStatus()!=DomainTypes.OrderStatus.CANCELLED;List<DomainTypes.OrderStatus> flow=o.getFulfillmentType()==DomainTypes.FulfillmentType.DELIVERY?List.of(DomainTypes.OrderStatus.RECEIVED,DomainTypes.OrderStatus.CONFIRMED,DomainTypes.OrderStatus.PREPARING,DomainTypes.OrderStatus.READY,DomainTypes.OrderStatus.OUT_FOR_DELIVERY,DomainTypes.OrderStatus.DELIVERED):List.of(DomainTypes.OrderStatus.RECEIVED,DomainTypes.OrderStatus.CONFIRMED,DomainTypes.OrderStatus.PREPARING,DomainTypes.OrderStatus.READY,DomainTypes.OrderStatus.DELIVERED);return flow.indexOf(n)==flow.indexOf(o.getStatus())+1;}
    private void addHistory(Order o,DomainTypes.OrderStatus s,String by){OrderStatusHistory h=new OrderStatusHistory();h.setOrder(o);h.setStatus(s);h.setChangedBy(by);o.getStatusHistory().add(h);}
    private OrderView map(Order o){List<OrderView.Item> items=o.getItems().stream().map(i->new OrderView.Item(i.getProductName(),i.getQuantity(),i.getUnitPrice(),i.getLineTotal(),i.getNotes(),i.getOptions().stream().map(OrderItemOption::getOptionName).toList())).toList();List<OrderView.Step> steps=o.getStatusHistory().stream().map(h->new OrderView.Step(h.getStatus(),h.getChangedAt())).toList();return new OrderView(o.getId(),o.getStatus(),o.getFulfillmentType(),o.getSubtotal(),o.getDeliveryFee(),o.getTotal(),o.getNotes(),o.getCreatedAt(),o.getAddress()==null?null:o.getAddress().formatted(),o.getPayment().getMethod(),o.getPayment().getChangeFor(),items,steps,o.getStatus()==DomainTypes.OrderStatus.DELIVERED&&!reviews.existsByOrderId(o.getId()),reviews.existsByOrderId(o.getId()),o.getStore().getSlug(),o.getStore().getName());}
    private <T extends Enum<T>>T parse(Class<T> c,String v,String msg){try{return Enum.valueOf(c,v);}catch(Exception e){throw new IllegalArgumentException(msg);}}private String clean(String v,int max){if(v==null)return "";String x=v.strip();return x.length()>max?x.substring(0,max):x;}
}
