-- V6: núcleo multitenant.
-- 1) Tabela stores recebe (100%) os dados da antiga store_settings singleton.
-- 2) Backfill cria a loja única com slug 'restaurante' (lowercase, sem espaços), active=true.
-- 3) Colunas store_id aditivas em categories, products, option_groups, orders e users
--    (todas as linhas existentes pertencem à loja migrada, id=1).
-- 4) A tabela store_settings é DROPADA ao final deste script: todos os seus dados já foram
--    copiados para stores (id=1) acima — nenhuma informação é perdida.
-- A UNIQUE global categories.name é tratada em V7 (script específico por banco: H2 e Postgres
-- geram nomes diferentes para constraints inline UNIQUE).

CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    slogan VARCHAR(200),
    description VARCHAR(600),
    phone VARCHAR(30),
    whatsapp VARCHAR(30),
    email VARCHAR(120),
    address_street VARCHAR(150),
    address_number VARCHAR(20),
    address_complement VARCHAR(100),
    address_neighborhood VARCHAR(100),
    address_city VARCHAR(100),
    address_state VARCHAR(2),
    address_zip VARCHAR(20),
    opening_hours TEXT,
    hero_title VARCHAR(200),
    hero_subtitle VARCHAR(400),
    delivery_time_note VARCHAR(120),
    delivery_fee NUMERIC(10,2) NOT NULL,
    brand_primary VARCHAR(7),
    brand_primary_dark VARCHAR(7),
    logo_path VARCHAR(300),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Backfill: dados da singleton store_settings (id=1) -> stores (id=1)
INSERT INTO stores (
    slug, name, slogan, description, phone, whatsapp, email,
    address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zip,
    opening_hours, hero_title, hero_subtitle, delivery_time_note, delivery_fee,
    brand_primary, brand_primary_dark, logo_path, active, created_at, updated_at
)
SELECT
    'restaurante',
    name, slogan, description, phone, whatsapp, email,
    address_street, address_number, address_complement, address_neighborhood, address_city, address_state, address_zip,
    opening_hours, hero_title, hero_subtitle, delivery_time_note, delivery_fee,
    brand_primary, brand_primary_dark, logo_path,
    TRUE,
    COALESCE(updated_at, CURRENT_TIMESTAMP),
    updated_at
FROM store_settings;

-- Colunas de escopo (aditivas, primeiro nullable para o backfill)
ALTER TABLE categories ADD COLUMN store_id BIGINT;
ALTER TABLE products ADD COLUMN store_id BIGINT;
ALTER TABLE option_groups ADD COLUMN store_id BIGINT;
ALTER TABLE orders ADD COLUMN store_id BIGINT;
ALTER TABLE users ADD COLUMN store_id BIGINT REFERENCES stores(id);

-- Backfill: tudo que existe hoje pertence à loja migrada (id=1)
UPDATE categories SET store_id = 1;
UPDATE products SET store_id = 1;
UPDATE option_groups SET store_id = 1;
UPDATE orders SET store_id = 1;
UPDATE users SET store_id = 1 WHERE role = 'ADMIN';

-- Fase 3: papel ADMIN passa a ser STORE_ADMIN vinculado à loja 1
UPDATE users SET role = 'STORE_ADMIN' WHERE role = 'ADMIN';

-- FKs + NOT NULL (exceto users.store_id: NULL para CUSTOMER)
ALTER TABLE categories ALTER COLUMN store_id SET NOT NULL;
ALTER TABLE products ALTER COLUMN store_id SET NOT NULL;
ALTER TABLE option_groups ALTER COLUMN store_id SET NOT NULL;
ALTER TABLE orders ALTER COLUMN store_id SET NOT NULL;
ALTER TABLE categories ADD CONSTRAINT fk_categories_store FOREIGN KEY (store_id) REFERENCES stores(id);
ALTER TABLE products ADD CONSTRAINT fk_products_store FOREIGN KEY (store_id) REFERENCES stores(id);
ALTER TABLE option_groups ADD CONSTRAINT fk_option_groups_store FOREIGN KEY (store_id) REFERENCES stores(id);
ALTER TABLE orders ADD CONSTRAINT fk_orders_store FOREIGN KEY (store_id) REFERENCES stores(id);

-- Índices de escopo
CREATE INDEX idx_categories_store_id ON categories(store_id);
CREATE INDEX idx_products_store_id ON products(store_id);
CREATE INDEX idx_option_groups_store_id ON option_groups(store_id);
CREATE INDEX idx_orders_store_id ON orders(store_id);
CREATE INDEX idx_users_store_id ON users(store_id);

-- store_settings foi 100% copiada para stores (id=1) neste script; removida com segurança.
DROP TABLE store_settings;
